// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVZ-M3kDyF-JUNQgKS6noIUQB-bBHXHM',
    appId: '1:358150375400:web:bc0852f4b6f3ea38ab865d',
    messagingSenderId: '358150375400',
    projectId: 'phurin-phuangmadue',
    authDomain: 'phurin-phuangmadue.firebaseapp.com',
    storageBucket: 'phurin-phuangmadue.firebasestorage.app',
    measurementId: 'G-78X6KKP5P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMzpbhNAZsl3Q8bdLR_-yRtJOBo-jLQZk',
    appId: '1:358150375400:android:d8107715ded524c8ab865d',
    messagingSenderId: '358150375400',
    projectId: 'phurin-phuangmadue',
    storageBucket: 'phurin-phuangmadue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeiclt7VjVu4efo1djUVf1UwKpAeO33s0',
    appId: '1:358150375400:ios:8e5c04d9d9ee706aab865d',
    messagingSenderId: '358150375400',
    projectId: 'phurin-phuangmadue',
    storageBucket: 'phurin-phuangmadue.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeiclt7VjVu4efo1djUVf1UwKpAeO33s0',
    appId: '1:358150375400:ios:8e5c04d9d9ee706aab865d',
    messagingSenderId: '358150375400',
    projectId: 'phurin-phuangmadue',
    storageBucket: 'phurin-phuangmadue.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnVZ-M3kDyF-JUNQgKS6noIUQB-bBHXHM',
    appId: '1:358150375400:web:63ef6267919d850aab865d',
    messagingSenderId: '358150375400',
    projectId: 'phurin-phuangmadue',
    authDomain: 'phurin-phuangmadue.firebaseapp.com',
    storageBucket: 'phurin-phuangmadue.firebasestorage.app',
    measurementId: 'G-KK8322BR10',
  );
}
